[package]
name = "Coil"
version = "0.1.0"
authors = ["Andrew Plaza <andrew.plaza@parity.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.3.5", features = ["postgres", "macros"] }
rayon = "1.3.1"
serde = "1.0.114"
async-trait = "0.1.36"
thiserror = "1.0.20"
rmp = "0.8.9"
