[package]
name = "coil"
version = "0.1.0"
authors = ["Andrew Plaza <andrew.plaza@parity.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.4.0-beta.1", features = ["postgres", "macros"] }
rayon = "1.3"
serde = "1.0"
serde_derive = "1.0"
rmp-serde = "0.14"
thiserror = "1.0"
inventory = "0.1"
coil_proc_macro = { path = "../coil_proc_macro" }
futures = "0.3.5"
async-trait = "0.1.36"
flume = "0.7.2"
timer = { version = "3.0", package = "futures-timer" }
once_cell = "1.4.0"
linkme = "0.2.2"

[features]
nightly = []
