[package]
name = "coil"
version = "0.1.0"
authors = ["Andrew Plaza <andrew.plaza@parity.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.4.0-beta.1", features = ["postgres", "macros"] }
rayon = "1.3"
serde = "1.0"
thiserror = "1.0"
inventory = "0.1"
rmp-serde = "0.14"
coil_proc_macro = { path = "../coil_proc_macro" }
serde_derive = "1.0"
smol = "0.3.3"
futures = "0.3.5"
async-trait = "0.1.36"

[features]
nightly = []
